services:
  whoami:
    restart: always
    labels:
      # make traefik use this sub-domain in entrypoint "https-ep" (as defined in traefik's docker-compose.base.yml)
      # we enable HTTP for localhost, only, and HTTPS for the "real" hostname
      - traefik.http.routers.whoami-service.entrypoints=https-ep
      - traefik.http.routers.whoami-service.rule=Host(`whoami.${HOSTNAME:?err}`)
      - traefik.http.routers.whoami-service.tls=true
      - traefik.http.routers.whoami-service.tls.certresolver=le

      # enable basic auth as defined in traefik's docker compose file
      - traefik.http.routers.whoami-service.middlewares=my-basic-auth